[package]
name = "data-processor"
version.workspace = true
edition.workspace = true
default-run = "data-processor"

[dependencies]
anyhow = "1.0.75"
bincode.workspace = true
common.path = "../common"
console = "0.15.7"
ctrlc = "3.4.1"
governor = "0.6.0"
indicatif = { version = "0.17.7", features = ["rayon"] }
rayon = "1.8.0"
reqwest = { version = "0.11.22", features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde-enum-str = "0.4"
serde_json = "1.0.108"
xz2 = "0.1.7"
zip = { version = "0.6.6", default-features = false }

[dependencies.image]
version = "0.24.7"
features = ["jpeg", "webp-encoder"]
default-features = false
