[package]
name = "data-processor"
version.workspace = true
edition.workspace = true
default-run = "data-processor"

[dependencies]
anyhow = "1.0.71"
bincode.workspace = true
common.path = "../common"
console = "0.15.7"
ctrlc = "3.4.0"
governor = "0.5.1"
indicatif = { version = "0.17.5", features = ["rayon"] }
rayon = "1.7.0"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.100"
xz2 = "0.1.7"
zip = { version = "0.6.6", default-features = false }

[dependencies.image]
version = "0.24.6"
features = ["jpeg", "webp-encoder"]
default-features = false
