[package]
name = "data-processor"
version.workspace = true
edition.workspace = true
default-run = "data-processor"

[dependencies]
anyhow = "1.0.81"
bincode.workspace = true
common.path = "../common"
console = "0.15.8"
ctrlc = "3.4.4"
governor = "0.6.3"
indicatif = { version = "0.17.8", features = ["rayon"] }
rayon = "1.9.0"
reqwest = { version = "0.11.26", features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde-enum-str = "0.4"
serde_json = "1.0.114"
xz2 = "0.1.7"
zip = { version = "0.6.6", default-features = false }

[dependencies.image]
version = "0.25.0"
features = ["jpeg", "webp"]
default-features = false
