[package]
name = "data-processor"
version.workspace = true
edition.workspace = true
default-run = "data-processor"

[dependencies]
anyhow = "1.0.86"
bincode.workspace = true
common.path = "../common"
console = "0.15.8"
ctrlc = "3.4.4"
futures = "0.3.30"
governor = "0.6.3"
indicatif = { version = "0.17.8", features = ["rayon"] }
pin-project = "1.1.5"
rayon = "1.10.0"
reqwest = { version = "0.12.4", features = ["json", "stream"] }
serde = { workspace = true, features = ["derive"] }
serde-enum-str = "0.4"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
tokio-serde = { version = "0.9.0", features = ["json"] }
tokio-util = { version = "0.7.11", features = ["compat"] }
xz2 = "0.1.7"
zip = { version = "1.3.0", default-features = false }

[dependencies.image]
version = "0.25.1"
features = ["jpeg", "webp"]
default-features = false
