[package]
name = "data-processor"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.70"
bincode.workspace = true
console = "0.15.5"
data.path = "../data"
indicatif = { version = "0.17.3", features = ["rayon"] }
rayon = "1.7.0"
reqwest = { version = "0.11.17", features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.96"
xz2 = "0.1.7"
