[package]
name = "ygo-deck-constructor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode.workspace = true
data.path = "data"
gloo-net.workspace = true
leptos.workspace = true
lzma-rs.workspace = true
nom.workspace = true
thiserror.workspace = true
wasm-bindgen-futures.workspace = true

[dev-dependencies]
itertools = "0.10"

[workspace]
members = ["data", "data-processor"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
bincode = "1.3"
clap = "4.1"
console = "0.15"
gloo-net = "0.2"
indicatif = "0.17"
leptos = { version = "0.1", features = ["stable"] }
lzma-rs = "0.3"
nom = "7.1"
rayon = "1.5"
reqwest = "0.11"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
wasm-bindgen-futures = "0.4"
xz2 = "0.1"
