[package]
name = "ygo-deck-constructor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode.workspace = true
common.path = "common"
console_error_panic_hook = "0.1.7"
gloo-dialogs = "0.2.0"
gloo-file = { version = "0.3.0", features = ["futures"] }
gloo-net = "0.5.0"
itertools = "0.12.1"
leptos = { version = "0.6.5", features = ["csr", "nightly"] }
leptos-use = "0.10.2"
lzma-rs = "0.3.0"
nom = "7.1.3"
thiserror = "1.0.56"
wasm-bindgen = "0.2.91"
wasm-bindgen-futures = "0.4.41"
web-sys = { version = "0.3.68", features = ["DataTransfer", "DragEvent", "DomRect"] }


[workspace]
members = ["common", "data-processor"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
bincode = "1.3.3"
serde = "1.0.196"
