[package]
name = "ygo-deck-constructor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode.workspace = true
common.path = "common"
console_error_panic_hook = "0.1.7"
gloo-net = "0.4.0"
leptos = { version = "0.4.10", features = ["csr", "nightly"] }
lzma-rs = "0.3.0"
nom = "7.1.3"
thiserror = "1.0.48"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["DataTransfer", "DragEvent"] }

[dev-dependencies]
itertools = "0.11.0"

[workspace]
members = ["common", "data-processor"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
bincode = "1.3.3"
serde = "1.0.188"
