[package]
name = "ygo-deck-constructor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode.workspace = true
console_error_panic_hook = "0.1.7"
data.path = "data"
gloo-net.workspace = true
leptos.workspace = true
lzma-rs.workspace = true
nom.workspace = true
thiserror.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { version = "0.3.61", features = ["DataTransfer", "DragEvent"] }

[dev-dependencies]
itertools = "0.10.5"

[workspace]
members = ["data", "data-processor"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.69"
bincode = "1.3.3"
clap = "4.1.6"
console = "0.15.5"
gloo-net = "0.2.6"
indicatif = "0.17.3"
leptos = "0.2.5" 
lzma-rs = "0.3.0"
nom = "7.1.3"
rayon = "1.6.1"
reqwest = "0.11.14"
serde = "1.0.152"
serde_json = "1.0.93"
thiserror = "1.0.38"
wasm-bindgen-futures = "0.4.34"
xz2 = "0.1.7"
