[package]
name = "common"
edition.workspace = true

[dependencies]
bincode.workspace = true
itertools.workspace = true
nom = "7.1.3"
rustc-hash.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror = "1.0.61"
