[package]
name = "common"
edition.workspace = true

[dependencies]
bincode.workspace = true
itertools.workspace = true
nom = "8.0.0"
rustc-hash.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror = "2.0.11"
