name: Deployment

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Install rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: nightly
                  target: wasm32-unknown-unknown

            - name: Install tools
              uses: taiki-e/install-action@v2
              with:
                  tool: trunk@0.18

            - name: Build
              run: trunk build --release --public-url=ygo-deck-constructor

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist/

    deploy:
        needs: build

        permissions:
            pages: write
            id-token: write

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
