name: Deployment

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Install rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: nightly
                  target: wasm32-unknown-unknown

            - name: Install trunk
              uses: jetli/trunk-action@v0.4.0

            - name: Build
              run: trunk build --release --public-url=ygo-deck-constructor

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: dist/
            - name: Deploy GitHub Pages site
              uses: actions/deploy-pages@v2
