name: Integration

on: [push, pull_request, workflow_dispatch]

jobs:
    checks:
        name: Run Checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Install rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: nightly
                  components: clippy, rustfmt

            - name: Install nasm
              uses: ilammy/setup-nasm@v1

            - name: Install tools
              uses: taiki-e/install-action@v2
              with:
                  tool: just, leptosfmt@0.1.30, cargo-machete

            - name: Run linter
              run: just lint

            - name: Run tests
              run: just test

            - name: Check formatting
              run: just check_fmt
