name: Integration

on: [push, pull_request, workflow_dispatch]

jobs:
    checks:
        name: Run Checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Install rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: nightly
                  components: clippy, rustfmt

            - name: Install just
              uses: baptiste0928/cargo-install@v2
              with:
                  crate: just
            - name: Install leptosfmt
              uses: baptiste0928/cargo-install@v2
              with:
                  crate: leptosfmt

            - name: Run linter
              run: just lint
            - name: Run tests
              run: just test
            - name: Check formatting
              run: just check_fmt
