name: Integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: clippy, rustfmt
    - name: Run linter
      run: just lint
    - name: Run tests
      run: just test
    - name: Check formatting
      run: cargo fmt --all -- --check
